# Generated by Django 5.0.6 on 2024-05-24 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artwork', models.URLField()),
                ('release_date', models.DateField(null=True)),
                ('original', models.BooleanField(default=True)),
                ('youtube', models.URLField(null=True)),
                ('ep', models.BooleanField(default=False)),
                ('alternatives', models.ManyToManyField(blank=True, to='music_api.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artwork', models.URLField()),
                ('release_date', models.DateField(null=True)),
                ('original', models.BooleanField(default=True)),
                ('youtube', models.URLField(null=True)),
                ('note', models.TextField(null=True)),
                ('mp3', models.URLField()),
                ('wav', models.URLField()),
                ('flac', models.URLField()),
                ('duration', models.IntegerField(default=0)),
                ('lyrics', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
                ('album', models.ManyToManyField(blank=True, to='music_api.album')),
                ('alternatives', models.ManyToManyField(blank=True, to='music_api.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('nickname', models.CharField(max_length=100)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.song')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.album')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_api.song')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('references_albums', models.ManyToManyField(blank=True, to='music_api.album')),
                ('references_songs', models.ManyToManyField(blank=True, to='music_api.song')),
            ],
        ),
    ]
