# Generated by Django 5.0.6 on 2024-05-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
