# Generated by Django 5.0.6 on 2024-05-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_alter_song_lyrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='albums',
        ),
    ]
