# Generated by Django 5.0.6 on 2024-05-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0004_rename_album_song_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='song_id',
            new_name='song',
        ),
    ]
