# Generated by Django 5.0.6 on 2024-05-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0005_rename_album_id_track_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
